name: ClemBot Prod Deployment

on:
  push:
    branches: [ master ]
    paths: 
      - "ClemBot.Api/**"
      - "ClemBot.Bot/**"
  workflow_dispatch:
    inputs:
      name:
        description: 'Manual ClemBot workflow trigger'
        required: true
        default: 'Manual Deployment'

jobs:
    deploy:
        name: Deploy
        runs-on: [self-hosted]
        steps:
            - uses: actions/checkout@v2
            - name: Copy Secrets
              run: |
                cp ~/ClemBot.Api_env.env ./ClemBot.Api/ClemBot.Api_env.env
                cp ~/ClemBot.Bot_env.env ./ClemBot.Bot/ClemBot.Bot_env.env
                cp ~/ClemBot.Site_env.env ./ClemBot.Bot/ClemBot.Site_env.env
            - name: Stop ClemBot Containers
              run: |
                docker stop $(docker ps -q)
            - name: Build updated Docker Images
              run: |
                ls
                docker-compose build
            - name: Deploy updated images
              run: |
                docker-compose up -d
            - name: Prune old images and containers
              run: |
                docker system prune -f
            - name: Discord notification
              env:
                DISCORD_WEBHOOK: ${{ secrets.WEBHOOK_URL }}
              uses: "Ilshidur/action-discord@0.3.0"
              with:
                args: 'The project {{ EVENT_PAYLOAD.repository.full_name }}/ClemBot.Api has been deployed.'
